---
- name: Set locale de_DE.UTF-8
  locale_gen:
    name: de_DE.UTF-8
    state: present
- name: Set timezone Europe/Berlin
  timezone:
    name: Europe/Berlin

- name: Set boot options
  lineinfile:
    dest: /boot/config.txt
    line: "{{ item }}"
    state: present
    insertafter: EOF
  with_items:
    - "disable_splash=1"
    - "disable_overscan=1"
    - "hdmi_force_hotplug=1"

- name: Set cmdline options
  copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: 0644

- apt: name=aptitude state=present
- name: Upgrade APT packages
  apt: >
    upgrade=yes
    update_cache=yes
    cache_valid_time=3600
- name: APT auto remove unneeded packages
  command: apt-get -y autoremove warn=no
  changed_when: False
- name: APT cleanup
  command: apt-get -y clean warn=no
  changed_when: False
