#!/bin/sh
xset -dpms     # disable DPMS (Energy Star) features.
xset s off     # disable screen saver  
xset s noblank # don't blank the video device
matchbox-window-manager -use_cursor no -use_titlebar no &
while true; do
    rm -rf /home/$USER/.cache/
    rm -rf /home/$USER/.config/
    /usr/bin/midori -e Fullscreen -a "file:///home/pi/teamcontrol-reader/raspberry_startup/wait.html"
    sleep 1
done
# unclutter &
# matchbox-window-manager & :
# xset -dpms
# xset s off
# while true; do
# /usr/bin/midori -e Fullscreen -a "file:///home/pi/teamcontrol-reader/raspberry_startup/wait.html"
# done
